Attempt to install coveralls in pipeline again

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -27,24 +27,22 @@ jobs:
       - name: Run tests with coverage
         run: npm run test:coverage
 
-      - name: Upload coverage report as artifact
+      - name: Upload coverage directory as artifact
         uses: actions/upload-artifact@v3
         with:
           name: coverage-report
           path: ./coverage/
 
-  upload-to-coveralls:
-    runs-on: ubuntu-latest
-    needs: test
-
-    steps:
-      - name: Download coverage report artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: coverage-report
-          path: ./coverage/
+      - name: Install Coveralls
+        run: npm install -g coveralls
 
       - name: Upload coverage to Coveralls
-        run: cat ./coverage/lcov.info | coveralls
+        run: |
+          if [ -f ./coverage/lcov.info ]; then
+            cat ./coverage/lcov.info | coveralls;
+          else
+            echo "lcov.info not found!";
+            exit 1;
+          fi
         env:
           COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
