Add action to download coverage artifact pushed and upload it to coveralls

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -1,4 +1,4 @@
-name: Generate Code Coverage
+name: Generate Code Coverage and Upload to Coveralls
 
 on:
   push:
@@ -27,8 +27,30 @@ jobs:
       - name: Run tests with coverage
         run: npm run test:coverage
 
-      - name: Upload coverage report
+      - name: Upload coverage report as artifact
         uses: actions/upload-artifact@v3
         with:
           name: coverage-report
+          path: ./coverage/
+
+  upload-to-coveralls:
+    runs-on: ubuntu-latest
+    needs: test
+
+    steps:
+      - name: Download coverage report artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: coverage-report
           path: ./coverage
+
+      - name: Upload coverage to Coveralls
+        run: |
+          if [ -f ./coverage/lcov.info ]; then
+            cat ./coverage/lcov.info | coveralls;
+          else
+            echo "lcov.info not found!";
+            exit 1;
+          fi
+        env:
+          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
